GET http://localhost:8080/recommendations/itemknncomparison?algorithm=ADJUSTEDCOSINE&numNeighbors=1000&aggregationApproach=mean
Accept: application/json

###
GET http://localhost:8080/recommendations/matrixfactorization?algorithm=BEMF&numFactors=10&numIterations=10&randomSeed=43
Accept: application/json